#!/bin/bash

if [ -z $1 ]
then
    echo Usage: install project-name
    exit 1
fi

echo Installing project $1...

ddev config --project-name=$1
ddev composer install &&
ddev composer run setup &&
ddev artisan vendor:publish --provider="Spatie\MediaLibrary\MediaLibraryServiceProvider" --tag="medialibrary-migrations"
ddev artisan migrate:fresh --seed &&
ddev describe &&
ddev launch
